[package]
name = "json-patch"
version = "1.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
categories = []
keywords = ["json", "json-patch"]
description = "RFC 6902, JavaScript Object Notation (JSON) Patch"
repository = "https://github.com/idubrov/json-patch"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"

[features]
default = ["diff"]
diff = []

[dependencies]
indexmap = "2.0.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0.40"
utoipa = { version = "3.3.0", optional = true }

[dev-dependencies]
expectorate = "1.0"
rand = "0.8.5"
serde_json = { version = "1.0.95", features = ["preserve_order"] }
serde_yaml = "0.9.19"
utoipa = { version = "3.3.0", features = ["debug"] }
